
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Create","number":103,"title":"Help Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/103"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Placeholders","number":102,"title":"Help Request Placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/102"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-table","number":99,"title":"Kk menu item review table component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/99"}]
