
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Create","number":103,"title":"Help Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/103"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Placeholders","number":102,"title":"Help Request Placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/102"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Table","number":100,"title":"Help Request Table Components","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/100"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-table","number":99,"title":"Kk menu item review table component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/99"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-component","number":97,"title":"Kk menu item review form component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/97"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Form","number":96,"title":"Help Request Form","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/96"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-index","number":95,"title":"Aneesh organization index","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/95"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"main","number":93,"title":"Merge pull request #81 from ucsb-cs156-s24/Kate-MenuItemCreatePage","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/93"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-create-page","number":92,"title":"Aneesh organization create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/92"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Fixtures","number":86,"title":"Help Request fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/86"}]
