
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequest-Page","number":113,"title":"Adil recommendation request page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/113"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-CreatePage","number":112,"title":"Help Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/112"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-edit","number":110,"title":"Aneesh organization edit","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/110"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-Table","number":107,"title":"Added Form Files and test for Articles","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/107"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequest-Table","number":106,"title":"Adil recommendation request table","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/106"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-placeholders","number":105,"title":"kk - copy placeholders for menu item review","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/105"}]
