
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HW5","number":144,"title":"HW05 Integration Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/144"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HW05","number":143,"title":"Help Request HW05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/143"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-hw5","number":142,"title":"June-HW5: Integration Test","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/142"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-H05-AddTests","number":141,"title":"Kate Larrick - Added E2E and integration testing for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/141"}]
