
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"Koray-H05","number":148,"title":"Koray H05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/148"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-HW5","number":147,"title":"Adil hw5","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/147"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh_hw","number":146,"title":"Aneesh hw #5 added tests for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/146"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HW5","number":144,"title":"HW05 Integration and End-to-End Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/144"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-hw5","number":142,"title":"June-HW5: Integration Test","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/142"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-H05-AddTests","number":141,"title":"Kate Larrick - Added E2E and integration testing for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/141"}]
