
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequestBackend","number":71,"title":"added backend for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/71"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemFixtures","number":63,"title":"Kate menu item fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/63"}]
