
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-Create","number":121,"title":"Create Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/121"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-CreatePage","number":120,"title":"kk - create page for menu item review","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/120"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-PlaceHolder","number":119,"title":"Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/119"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-TrueTable","number":116,"title":" Table + Form Component for Articles plus test","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/116"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-EditPage","number":115,"title":"Help Request Edit Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/115"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-IndexPage","number":114,"title":"Help Request Index Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/114"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequest-Page","number":113,"title":"Adil recommendation request page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/113"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-CreatePage","number":112,"title":"Help Request Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/112"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-edit","number":110,"title":"Aneesh organization edit","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/110"}]
