
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemIndex","number":89,"title":"Kate menu item index","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/89"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-new-placeholders","number":88,"title":"Aneesh organization new placeholders","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/88"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Fixtures","number":86,"title":"Help Request fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/86"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequest-Backend","number":85,"title":"Add Help Request Backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/85"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemEditPage","number":84,"title":"Kate menu item edit page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/84"},{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-fixture","number":82,"title":"kk - menu item review fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/82"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemCreatePage","number":81,"title":"Kate menu item create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/81"}]
