
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemForm","number":75,"title":"Kate menu item form","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/75"},{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-organization-form","number":74,"title":"form components","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/74"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-fixture","number":72,"title":"Create fixtures for Articles","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/72"}]
