
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequest-IndexPage","number":126,"title":"Adil recommendation request index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/126"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequest-EditPage","number":124,"title":"Adil recommendation request edit page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/124"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-Create","number":121,"title":"Create Page for Articles plus tests and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/121"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-PlaceHolder","number":119,"title":"Copy Placeholders for Articles pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-7/pull/119"}]
